Resources:
  GamesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "gameId"
          AttributeType: "S"
        - AttributeName: "gameTime"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "gameId"
          KeyType: "HASH"
        - AttributeName: "gameTime"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "games"
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "userId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "userId"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "users"