Resources:
  GamesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "gameId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "gameId"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "Games"
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "userId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "userId"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "Users"